import Head from "next/head";
import SubmitForm from "../components/SubmitForm/Index";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Test Task</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../assets/images/fav.png" />
      </Head>

      <SubmitForm />
    </div>
  );
}
